# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentsaegis < Formula
  desc "Security awareness proxy for AI coding tools"
  homepage "https://github.com/agentsaegis/go-proxy"
  version "0.9.0"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentsaegis/go-proxy/releases/download/v0.9.0/agentsaegis_0.9.0_darwin_amd64.tar.gz"
      sha256 "08c43ef884f26e3c1e481b1a730d771502edc5a6db6e894fb7f661c735138b31"

      define_method(:install) do
        bin.install "agentsaegis"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentsaegis/go-proxy/releases/download/v0.9.0/agentsaegis_0.9.0_darwin_arm64.tar.gz"
      sha256 "98a060e91c43e15d8111276cb1ec5a4b6261790ce8b35f6c38109e79da1daed6"

      define_method(:install) do
        bin.install "agentsaegis"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentsaegis/go-proxy/releases/download/v0.9.0/agentsaegis_0.9.0_linux_amd64.tar.gz"
      sha256 "b1a2c4926f017c7876c3fe5ea3187e55a9ec5edcd9501e0d636ac32c15bab8fa"
      define_method(:install) do
        bin.install "agentsaegis"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentsaegis/go-proxy/releases/download/v0.9.0/agentsaegis_0.9.0_linux_arm64.tar.gz"
      sha256 "c46141bf2336aaadb4c1e596047454827285f00f8a2a92aaa706c2f90e26b24f"
      define_method(:install) do
        bin.install "agentsaegis"
      end
    end
  end

  test do
    system "#{bin}/agentsaegis", "--version"
  end
end
