# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentsaegis < Formula
  desc "Security awareness proxy for AI coding tools"
  homepage "https://github.com/agentsaegis/go-proxy"
  version "0.11.3"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentsaegis/go-proxy/releases/download/v0.11.3/agentsaegis_0.11.3_darwin_amd64.tar.gz"
      sha256 "f02d766dd6690f65e8fd545e2e77bbeb739f93492224b69d11b26f12fd6e0ad2"

      define_method(:install) do
        bin.install "agentsaegis"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentsaegis/go-proxy/releases/download/v0.11.3/agentsaegis_0.11.3_darwin_arm64.tar.gz"
      sha256 "82514c2569d5b7512e968fd3b8ef48e700987ce80fe2e2a44403bfa792d3fab1"

      define_method(:install) do
        bin.install "agentsaegis"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentsaegis/go-proxy/releases/download/v0.11.3/agentsaegis_0.11.3_linux_amd64.tar.gz"
      sha256 "4197ecf6736cdc52bc9e35cdd7b7f0f5f2e8ba90c602f9d6277cb02cd15d5002"
      define_method(:install) do
        bin.install "agentsaegis"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentsaegis/go-proxy/releases/download/v0.11.3/agentsaegis_0.11.3_linux_arm64.tar.gz"
      sha256 "ae46d5f5a3893af67b233a86b17583dc841cb3382517d2cafef5797d41b45ebc"
      define_method(:install) do
        bin.install "agentsaegis"
      end
    end
  end

  test do
    system "#{bin}/agentsaegis", "--version"
  end
end
