# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentsaegis < Formula
  desc "Security awareness proxy for AI coding tools"
  homepage "https://github.com/agentsaegis/go-proxy"
  version "0.10.0"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentsaegis/go-proxy/releases/download/v0.10.0/agentsaegis_0.10.0_darwin_amd64.tar.gz"
      sha256 "1e63602be22ef02ec0ee2a86ab85140a6e0d8496780879c5cdb0ee0d1466c7d6"

      define_method(:install) do
        bin.install "agentsaegis"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentsaegis/go-proxy/releases/download/v0.10.0/agentsaegis_0.10.0_darwin_arm64.tar.gz"
      sha256 "cce920bb440b43fd12b8896d5486b90ef535689f4d5123d062c17bc11790a547"

      define_method(:install) do
        bin.install "agentsaegis"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentsaegis/go-proxy/releases/download/v0.10.0/agentsaegis_0.10.0_linux_amd64.tar.gz"
      sha256 "504fc5dd0eefc9c8b0178384deeab52775566a2be172931722bfef153cbbf351"
      define_method(:install) do
        bin.install "agentsaegis"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentsaegis/go-proxy/releases/download/v0.10.0/agentsaegis_0.10.0_linux_arm64.tar.gz"
      sha256 "fe55cf76712518524ccd4561cefecdb559988f17d7d005c9d7617c5eb945b2f3"
      define_method(:install) do
        bin.install "agentsaegis"
      end
    end
  end

  test do
    system "#{bin}/agentsaegis", "--version"
  end
end
