# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoProxy < Formula
  desc "Security awareness proxy for AI coding tools"
  homepage "https://github.com/agentsaegis/go-proxy"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentsaegis/go-proxy/releases/download/v0.4.0/go-proxy_0.4.0_darwin_amd64.tar.gz"
      sha256 "54bff01f8447f320d7ce46b30bb0d8f150c003b446ca9d2e73d34dcec84a0ae8"

      define_method(:install) do
        bin.install "agentsaegis"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentsaegis/go-proxy/releases/download/v0.4.0/go-proxy_0.4.0_darwin_arm64.tar.gz"
      sha256 "ccafe43b85982093b43060cad7e58f014c37b3d2763f726138f308ea20ea7361"

      define_method(:install) do
        bin.install "agentsaegis"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentsaegis/go-proxy/releases/download/v0.4.0/go-proxy_0.4.0_linux_amd64.tar.gz"
      sha256 "fd879929e0d9fc57968f485a485c3901d9ba7ac44594bd555bb749ae8358ca87"
      define_method(:install) do
        bin.install "agentsaegis"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentsaegis/go-proxy/releases/download/v0.4.0/go-proxy_0.4.0_linux_arm64.tar.gz"
      sha256 "1009dc025388cb3961d7f921da05654f7dbbd9a3b56b84d9aa157b1e438521a5"
      define_method(:install) do
        bin.install "agentsaegis"
      end
    end
  end

  test do
    system "#{bin}/agentsaegis", "--version"
  end
end
